name: CI

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      web:
        image: node:14
        ports:
          - 3000:3000
        options: >-
          --health-cmd="curl --fail http://localhost:3000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      api:
        image: python:3.8
        ports:
          - 8000:8000
        options: >-
          --health-cmd="curl --fail http://localhost:8000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Start React app
        run: npm start &
        env:
          CI: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Django dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Start Django app
        run: |
          . venv/bin/activate
          python manage.py runserver &
        env:
          DJANGO_SETTINGS_MODULE: your_project.settings

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
        env:
          CYPRESS_baseUrl: http://localhost:3000
          API_URL: http://localhost:8000